import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { getListing } from '@/features/books/queries'
import { getSessionUser } from '@/lib/auth/dal'
import { formatItemCode, itemUrlFor, qrSvgFor } from '@/lib/qr'
import { KIND_COPY } from '@/types/domain'
import styles from './page.module.css'

export const metadata = {
  title: 'QR',
  robots: { index: false, follow: false },
}

/**
 * The label that goes inside the book.
 *
 * Printed once and stuck to the thing, which is what makes a café shelf work:
 * whoever is holding it can say what it is without the owner being present.
 *
 * One label, as large as the column allows. It was two for a while, on the
 * theory that a second copy could go on a shelf edge or in a ledger — nobody
 * asked for that, and the pair only raised the question of which one was the
 * real one. A bigger symbol also scans from further away and survives a worse
 * printer.
 *
 * The QR is inline SVG generated on the server, so printing it is exact at any
 * size and there is no image request to fail.
 */
export default async function LabelPage({ params }: PageProps<'/books/[copyId]/label'>) {
  const { copyId } = await params
  const [listing, me] = await Promise.all([getListing(copyId), getSessionUser()])
  if (!listing) notFound()
  // The code is not a secret — it is printed on the object — but the page that
  // hands out a fresh sheet of them is the owner's.
  if (!me) redirect(`/login?next=/books/${copyId}/label`)
  if (me.id !== listing.owner?.id) redirect(`/books/${copyId}`)

  const code = listing.publicCode
  const svg = await qrSvgFor(code)
  const pretty = formatItemCode(code)

  return (
    <div className="container">
      <div className={styles.shell}>
        <div className={styles.toolbar}>
          <Link href={`/books/${copyId}`} className={styles.back}>
            ← Буцах
          </Link>
          <p className={styles.help}>
            Хэвлээд ном, пянздаа наа — эсвэл дэлгэцээ шууд уншуулж болно. Хэн нэгэн
            уншуулбал энэ зүйл нь юу болох, хэн эзэмшдэгийг харна.
          </p>
        </div>

        <div className={styles.sheet}>
          <div className={styles.label}>
            <div
              className={styles.qr}
              // Generated by the QR encoder from a URL this app built; no user
              // input reaches it.
              dangerouslySetInnerHTML={{ __html: svg }}
            />
            <div className={styles.text}>
              <p className={styles.code}>{pretty}</p>
              <p className={styles.title}>{listing.title}</p>
              <p className={styles.kind}>
                {KIND_COPY[listing.kind].one} · {listing.owner?.displayName} · solio.mn
              </p>
            </div>
          </div>
        </div>

        <p className={styles.url}>{itemUrlFor(code)}</p>
      </div>
    </div>
  )
}
